[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"  # Only if using Netlify functions

[context.production]
  environment = { 
    NODE_VERSION = "18" 
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://cloud.appwrite.io;
      connect-src 'self' https://cloud.appwrite.io;
      font-src 'self';
      frame-ancestors 'none';
    """